<?php
// See the list of removed categories at the end of this file.
$items = array (
	'Any' => 'Any (except Feature Requests)',

	'*General Issues' => 'General Issues',
	'Feature/Change Request'   => '&nbsp;&nbsp;&nbsp;&nbsp;Feature/Change Request',
	'Documentation problem'    => '&nbsp;&nbsp;&nbsp;&nbsp;Documentation problem',
	'Translation problem'      => '&nbsp;&nbsp;&nbsp;&nbsp;Documentation translation problem',
	'Doc Build problem'        => '&nbsp;&nbsp;&nbsp;&nbsp;Doc Build (PhD) problem',
	'Website problem'          => '&nbsp;&nbsp;&nbsp;&nbsp;PHP.net Website problem',
	'Systems problem'          => '&nbsp;&nbsp;&nbsp;&nbsp;PHP.net Systems Operation problem',
	'Output Control'           => '&nbsp;&nbsp;&nbsp;&nbsp;Output Control',
	'Performance problem'      => '&nbsp;&nbsp;&nbsp;&nbsp;Performance problem',
	'Reproducible crash'       => '&nbsp;&nbsp;&nbsp;&nbsp;Reproducible crash',
	'Scripting Engine problem' => '&nbsp;&nbsp;&nbsp;&nbsp;Scripting Engine problem',
	'SPL related'              => '&nbsp;&nbsp;&nbsp;&nbsp;SPL related',
	'Reflection related'       => '&nbsp;&nbsp;&nbsp;&nbsp;Reflection related',
	'Session related'          => '&nbsp;&nbsp;&nbsp;&nbsp;Session related',
	'Filter related'           => '&nbsp;&nbsp;&nbsp;&nbsp;Filter related',
	'Streams related'          => '&nbsp;&nbsp;&nbsp;&nbsp;Streams related',
	'PHP-GTK related'          => '&nbsp;&nbsp;&nbsp;&nbsp;PHP-GTK related',
	'PDO related'              => '&nbsp;&nbsp;&nbsp;&nbsp;PDO related',
	'PHAR related'             => '&nbsp;&nbsp;&nbsp;&nbsp;PHAR related',

	'*Compile Issues' => '&nbsp;&nbsp;&nbsp;&nbsp;Compile Issues',
	'Compile Failure' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Compile Failure',
	'Compile Warning' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Compile Warning',

	'*Configuration Issues'      => '&nbsp;&nbsp;&nbsp;&nbsp;Configuration Issues',
	'Dynamic loading'            => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dynamic loading',
	'PHP options/info functions' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; PHP options/info functions',
	'Safe Mode/open_basedir'     => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Safe Mode/open_basedir related',
	'Windows Installer'          => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Windows Installer related',

	'*Web Server problem' => '&nbsp;&nbsp;&nbsp;&nbsp;Web Server problem',
	'CGI related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; CGI/CLI related',
	'Apache related'      => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Apache related',
	'Apache2 related'     => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Apache2 related',
	'IIS related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; IIS related',
	'iPlanet related'     => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; iPlanet related',
	'PWS related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; PWS related',
	'Servlet related'     => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Servlet related',
	'Other web server'    => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Other web server',

	'*Calendar problems' => '&nbsp;&nbsp;&nbsp;&nbsp;Calendar problems',
	'Date/time related'  => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date/time related',
	'Calendar related'   => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Calendar related',

	'*Compression related' => '&nbsp;&nbsp;&nbsp;&nbsp;Compression related',
	'Bzip2 Related'        => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Bzip2 Related',
	'Zip Related'          => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Zip Related',
	'ZZiplib Related'      => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ZZiplib Related',
	'Zlib Related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Zlib Related',

	'*Directory/Filesystem functions' => '&nbsp;&nbsp;&nbsp;&nbsp;Directory/Filesystem functions',
	'Directory function related'      => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Directory function related',
	'Filesystem function related'     => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Filesystem function related',

	'*Directory Services problems' => '&nbsp;&nbsp;&nbsp;&nbsp;Directory Services problems',
	'LDAP related'                 => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; LDAP related',

	'*Database Functions'       => '&nbsp;&nbsp;&nbsp;&nbsp;Database Functions',
	'Adabas-D related'          => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Adabas-D related',
	'dBase related'             => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; dBase related',
	'DBM/DBA related'           => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DBM/DBA related',
	'DBX related'               => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DBX related',
	'FrontBase related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; FrontBase related',
	'Informix related'          => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Informix related',
	'Ingres II related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ingres II related',
	'InterBase related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; InterBase related',
	'mSQL related'              => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; mSQL related',
	'MSSQL related'             => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MSSQL related',
	'MySQL related'             => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MySQL related',
	'MySQLi related'            => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MySQLi related',
	'OCI8 related'              => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; OCI8 related',
	'Oracle related'            => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Oracle related',
	'ODBC related'              => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ODBC related',
	'PostgreSQL related'        => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; PostgreSQL related',
	'Solid related'             => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Solid related',
	'SQLite related'            => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SQLite related',
	'Sybase (dblib) related'    => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sybase (dblib) related',
	'Sybase-ct (ctlib) related' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sybase-ct (ctlib) related',

	'*Data Exchange functions' => '&nbsp;&nbsp;&nbsp;&nbsp;Data Exchange functions',
	'JSON related'             => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; JSON related',
	'WDDX related'             => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; WDDX related',

	'*Extensibility Functions' => '&nbsp;&nbsp;&nbsp;&nbsp;Extensibility Functions',
	'COM related'              => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; COM related',
	'Java related'             => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Java related',
	'ncurses related'          => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ncurses related',
	'Program Execution'        => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Program Execution',
	'POSIX related'            => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; POSIX functions related',
	'PCNTL related'            => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; PCNTL related',
	'Readline related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Readline related',
	'Semaphore related'        => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Semaphore related',
	'Win32API related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Win32API related',

	'*E-commerce functions'        => '&nbsp;&nbsp;&nbsp;&nbsp;E-commerce functions',
	'Verisign Payflow Pro related' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Verisign Payflow Pro related',

	'*Graphics related'    => '&nbsp;&nbsp;&nbsp;&nbsp;Graphics related',
	'EXIF related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; EXIF related',
	'GD related'           => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GD related',
	'GetImageSize related' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GetImageSize related',
	'Ming related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ming related',

	'*Languages/Translation' => '&nbsp;&nbsp;&nbsp;&nbsp;Languages/Translation',
	'Gettext related'        => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Gettext related',
	'ICONV related'          => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ICONV related',
	'mbstring related'       => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; MBstring related',
	'Recode related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Recode related',

	'*Mail Related'      => '&nbsp;&nbsp;&nbsp;&nbsp;Mail Related',
	'IMAP related'       => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; IMAP related',
	'Mail related'       => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; mail function related',

	'*Math Functions' => '&nbsp;&nbsp;&nbsp;&nbsp;Math Functions',
	'BC math related' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; BC math related',
	'GNU MP related'  => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; GNU MP related',
	'Math related'    => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Math related',

	'*Encryption and hash functions' => '&nbsp;&nbsp;&nbsp;&nbsp;Encryption and hash functions',
	'mcrypt related'                 => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; mcrypt related',
	'mhash related'                  => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; mhash related',
	'OpenSSL related'                => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; OpenSSL related',

	'*Network Functions' => '&nbsp;&nbsp;&nbsp;&nbsp;Network Functions',
	'Network related'    => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Network related',
	'SNMP related'       => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SNMP related',
	'FTP related'        => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; FTP related',
	'HTTP related'       => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; HTTP related',
	'Sockets related'    => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sockets related',

	'*PDF functions'  => '&nbsp;&nbsp;&nbsp;&nbsp;PDF functions',
	'ClibPDF related' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ClibPDF related',
	'FDF related'     => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; FDF related',
	'PDF related'     => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; PDF related',

	'*Programming Data Structures' => '&nbsp;&nbsp;&nbsp;&nbsp;Programming Data Structures',
	'Class/Object related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Class/Object related',
	'Arrays related'               => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Arrays related',
	'Strings related'              => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Strings related',
	'Variables related'            => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Variables related',

	'*Regular Expressions' => '&nbsp;&nbsp;&nbsp;&nbsp;Regular Expressions',
	'PCRE related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; PCRE related',
	'Regexps related'      => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Regexps related',

	'*Spelling functions' => '&nbsp;&nbsp;&nbsp;&nbsp;Spelling functions',
	'Pspell related'      => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pspell related',

	'*Search functions'   => '&nbsp;&nbsp;&nbsp;&nbsp;Search functions',
	'mnoGoSearch related' => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; mnoGoSearch related',

	'*XML functions'      => '&nbsp;&nbsp;&nbsp;&nbsp;XML functions',
	'DOM XML related'     => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; DOM XML related',
	'SOAP related'        => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SOAP related',
	'SimpleXML related'   => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; SimpleXML related',
	'XML Reader'          => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; XML Reader',
	'XML Writer'          => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; XML Writer',
	'XML related'         => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; XML related',
	'XMLRPC-EPI related'  => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; XMLRPC-EPI related',
	'XSLT related'        => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; XSLT related',

	'*URL Functions' => '&nbsp;&nbsp;&nbsp;&nbsp;URL Functions',
	'cURL related'   => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cURL related',
	'URL related'    => '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; URL related',

	'*Unicode Issues'                   => 'Unicode Issues',
	'Unicode Function Upgrades related' => '&nbsp;&nbsp;&nbsp;&nbsp;Unicode Function Upgrades related',
	'I18N and L10N related'             => '&nbsp;&nbsp;&nbsp;&nbsp;I18N and L10N related',
	'Unicode Engine related'            => '&nbsp;&nbsp;&nbsp;&nbsp;Unicode Engine related',

	'Unknown/Other Function' => 'Unknown/Other Function',
);

/*
Removed categories:
 - Livedocs problem : Replaced with a new doc build system named PhD

 Previously when we removed categories from bugsweb, we would re-categorize them as "Unknown/Other Function" 
 but rather than lose category information this has changed... the categories are now kept. 
 
 Perhaps in the future we can add the ability to search (but not add/comment) the removed categories via the 
 form instead of manually typing the category name as done currently. But, in theory, people don't care about 
 these "orphaned" bugs. Later let's discuss this for the new bug system.
*/
