<?php

require_once 'prepend.inc';

commonHeader('Show Source');

if (!isset($_GET['url'])) {
    echo 'No page URL specified.';
    commonFooter();
    exit;
}
$out_url = htmlspecialchars($_GET['url'], ENT_QUOTES);
echo "Source of: $out_url<br />\n", hdelim(); 

$legal_dirs = array (
	'manual'  => 1,
	'include' => 1,
	'stats'   => 1,
);
$dir = dirname($_GET['url']);
$basedir = dirname(__FILE__);
if ($dir && isset($legal_dirs[$dir])) {
	$page_name = "$basedir/$out_url";
} else {
	$page_name = basename($out_url);
}

echo("<!-- $page_name -->\n");

if (file_exists($page_name) && !is_dir($page_name)) {
	show_source($page_name);
} else if (is_dir($page_name)) {
	echo "<p>No file specified.  Can't show source for a directory.</p>\n";
}

echo hdelim(); 

?>
<p>
The syntax highlighted source is automatically generated by PHP from the plaintext script.<br />
If you're interested in what's behind the <b>commonHeader()</b> and <b>commonFooter()</b> functions, 
you can always take a look at the source of the 
<?php print_link('source.php?url=include/layout.inc', 'layout.inc'); ?> files.
And, of course, if you want to see the source of this page, have a look
<?php print_link('source.php?url=source.php', 'here'); ?>.
</p>
<?php

commonFooter();
