#!/usr/bin/env php
<?php /* vim: set ft=phpbugdb noet ts=4 sw=4 : */

# this script closes bugs due to lack of feedback.

require __DIR__.'/../../include/prepend.php';

# date interval to close after
$after = "7 DAY";

# Set "input" array
$in = ['status' => 'No Feedback'];

# Update relevant reports
if ($dbh)
{
	list($RESOLVE_REASONS, $FIX_VARIATIONS) = get_resolve_reasons($site);

	$res = $dbh->prepare("
		SELECT id, package_name, bug_type, email, passwd, sdesc, ldesc, php_version,
			php_os, status, ts1, ts2, assign, UNIX_TIMESTAMP(ts1) AS submitted,
			private, reporter_name, UNIX_TIMESTAMP(ts2) AS modified
		FROM bugdb
		WHERE status = 'Feedback' AND ts2 < DATE_SUB(NOW(), INTERVAL {$after})
	")->execute([]);
	if (PEAR::isError($res)) {
		throw new Exception("SQL Error in no-feedback");
	}
	while ($bug = $res->fetchRow(PDO::FETCH_ASSOC))
	{
		list($mailto, $mailfrom, $bcc, $params) = get_package_mail($bug['package_name'], false, $bug['bug_type']);

		// No feedback message
		if (isset($FIX_VARIATIONS) && isset($FIX_VARIATIONS['nofeedback'][$bug['package_name']])) {
			$message = $FIX_VARIATIONS['nofeedback'][$bug['package_name']];
		} elseif (isset($RESOLVE_REASONS['nofeedback'])) {
			$message = $RESOLVE_REASONS['nofeedback']['message'];
		} else {
			die('[no-feedback] Could not find resolve reason! (this should not happen!)');
		}
		bugs_add_comment($bug['id'], $mailfrom, '', $message, 'comment');

		// Update status
		$dbh->prepare('
			UPDATE bugdb
			SET status = "No Feedback", ts2 = NOW()
			WHERE id = ?
		')->execute([
			$bug['id'],
		]);

		// Send emails
		mail_bug_updates($bug, $in, $mailfrom, $message);
	}
}
