#!/usr/bin/env php
<?php

/**
 * Main command line console entry application.
 *
 * SYNOPSIS:
 *   php scripts/console [command] [<options>] [arguments]
 */

require_once __DIR__.'/../include/prepend.php';

use Symfony\Component\Console\Application;

$container->get(Application::class)->run();
