#!/usr/local/bin/php -q
<?php
	if ($argc == 2) {
		$version = $argv[1];
	} else {
		$version = '4';
	}
	if (!in_array($version, array(4,5,6,'Irrelevant'))) {
		$version = '4';
	}
	mysql_connect("localhost","nobody","") or die("Unable to connect to SQL server\n");
	mysql_select_db("phpbugdb");
	$result = mysql_query("select id,bug_type,status,sdesc,assign from bugdb where status not in ('Closed', 'Bogus', 'Duplicate', 'No Feedback', 'Wont fix') and php_version like '$version%' order by bug_type,id");
	if (!is_numeric($version)) {
		$version = '';
	}
	if($num=mysql_num_rows($result)) {
		$body = " PHP $version Bug Database summary - http://bugs.php.net\n\n";
		$body .= " Num Status     Summary ($num total including feature requests)\n";
		$last_group = "";
		while($row = mysql_fetch_assoc($result)) {
			if($row['status']=='Assigned') {
				$ass[$row['assign']][$row['id']] = $row['sdesc'];
			}
			if($last_group!=$row['bug_type']) {
				$last_group = $row['bug_type'];
				$body .= "===============================================[".$row['bug_type']."]";
				$len = 29-strlen($row['bug_type']);
				for($i=0;$i<$len; $i++) $body .= "=";
				$body .= "\n";
			}
			$body .= sprintf("%4d ",$row['id']);
			$body .= sprintf("%-9s ",$row['status']);
			$body .= " ".$row['sdesc']."\n";
		}
		mysql_free_result($result);
		$body .= "\nAssigned bugs: (reminders sent)\n";
		while(list($k,$v)=each($ass)) {
			while(list($kk,$vv)=each($v)) {
				$body .= "$k\t\t$kk: $vv\n";
				$send[$k] .= "http://bugs.php.net/$kk\t: $vv\n";
			}
		}
		while(list($k,$v)=each($send)) {
			if(strstr($k,'@')) {
				mail($k,"Assigned PHP bugs reminder",$v,"From: internals@lists.php.net");
			} else {
				mail("$k@php.net","Assigned PHP $version bugs reminder",$v,"From: internals@lists.php.net");
			}
		}
		if ($version) {
			mail("internals@lists.php.net","PHP $version Bug Summary Report",$body,"From: internals@lists.php.net");
		}
	}	
?>
