#!/usr/local/bin/php -q
<?php /* vim: set ft=phpbugdb noet ts=4 sw=4 : */

require dirname(__FILE__).'/../include/functions.inc';

# this script closes bugs due to lack of feedback.

# date interval to close after
$after = "7 DAY";

$message =
'No feedback was provided for this bug for over a week, so it is
being suspended automatically. If you are able to provide the
information that was originally requested, please do so and change
the status of the bug back to "Open".';

$mail_bugs_to = 'php-bugs@lists.php.net';

mysql_connect("localhost", "nobody", "")
  or die("unable to connect to database");
mysql_select_db("phpbugdb")
  or die("unable to select db");

# fetch info about the bug into $bug
$query = "
  SELECT id, bug_type, email, passwd, sdesc, ldesc, php_version, php_os, status, ts1, ts2, assign,
         UNIX_TIMESTAMP(ts1) AS submitted, UNIX_TIMESTAMP(ts2) AS modified
  FROM bugdb
  WHERE status = 'Feedback' AND ts2 < DATE_SUB(NOW(),INTERVAL $after)
";

$result = mysql_query($query)
  or die("query failed: ".mysql_error()."\n$query");

$in = array('status' => 'No Feedback');

while ($bug = mysql_fetch_assoc($result)) {
  list($mailto,$mailfrom) = get_bugtype_mail($bug['bug_type']);

  mysql_query("INSERT bugdb_comments SET bug=$bug[id],email='$mailfrom',ts=NOW(),comment='".addslashes($message)."'");
  mysql_query("UPDATE bugdb SET status='No Feedback',ts2=NOW() WHERE id=$bug[id]");

  mail_bug_updates($bug,$in,$mailfrom,$message);
}
