#!/usr/local/bin/php -q
<?php /* vim: set ft=phpbugdb noet ts=4 sw=4 : */

require dirname(__FILE__).'/../include/functions.inc';

# this script closes PHP 3 bugs (without emails)

$mailfrom = 'php-bugs@lists.php.net';
$message = 'We are sorry, but we do not support PHP 3 related problems anymore.';

$db = mysql_connect("localhost", "nobody", "")
  or die("unable to connect to database");
mysql_select_db("phpbugdb", $db)
  or die("unable to select db");

# fetch info about the bug into $bug
$query = "
  SELECT id 
  FROM bugdb
  WHERE SUBSTRING(php_version,1,1) = '3' AND status NOT IN ('Wont fix', 'Bogus', 'Closed')
";

$result = mysql_query($query, $db)
  or die("query failed: ".mysql_error($db)."\n$query");

while ($bug = mysql_fetch_assoc($result)) {
  mysql_query("INSERT bugdb_comments SET bug=$bug[id],email='$mailfrom',ts=NOW(),comment='".addslashes($message)."'");
  mysql_query("UPDATE bugdb SET status='Wont fix',ts2=NOW() WHERE id=$bug[id]");
}
